name: Github page deploy

on:
    push:
        branches:
            - "v2"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install and build
              env:
                  REACT_APP_EMAIL_SERVICE_ID: "${{ secrets.REACT_APP_EMAIL_SERVICE_ID }}"
                  REACT_APP_EMAIL_PUBLIC_ID: "${{ secrets.REACT_APP_EMAIL_PUBLIC_ID }}"
                  REACT_APP_EMAIL_TEMPLATE: "${{ secrets.REACT_APP_EMAIL_TEMPLATE }}"
              run: |
                  echo " Secrets ${{ env.REACT_APP_EMAIL_SERVICE_ID }}, ${{ env.REACT_APP_EMAIL_PUBLIC_ID }}, ${{ env.REACT_APP_EMAIL_TEMPLATE }} " |
                  npm install --force && npm run build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  branch: gh-pages
                  folder: build
